version: "3"
services:
  app:
    image: laravel-www
    container_name: application
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - redis
      - mysql
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis
      
  redis:
    container_name: redis4
    image: redis:4-alpine
    ports:
      - 16379:6379
    volumes:
      - redis:/data

  mysql:
    container_name: mysql5
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root

volumes:
  redis:
    driver: "local"
  mysql:
    driver: "local"